# Updated automatically by .github/workflows/update-upstream.yml
ARG XUI_VERSION=v3.6.0
FROM ghcr.io/mhsanaei/3x-ui:${XUI_VERSION}
USER root
RUN apk add --no-cache nginx sqlite jq
COPY gucci /app/gucci
RUN chmod 0755 /app/gucci/entrypoint.sh
ENV PORT=1 \
    GUCCI_PUBLIC_PORT=1 \
    XUI_ENABLE_FAIL2BAN=true \
    XUI_DB_FOLDER=/data/x-ui \
    XUI_INTERNAL_PORT=2053 \
    XUI_WEB_BASE_PATH=/gucci/ \
    XUI_DATA_ROOT=/data \
    XUI_FORCE_INITIAL_CREDENTIALS=false \
    XUI_BOOTSTRAP_INBOUND=true \
    GUCCI_INBOUND_PORT=1234 \
    GUCCI_REALITY_TARGET=yahoo.com:443 \
    GUCCI_REALITY_SNI=s.yimg.com
EXPOSE 1
ENTRYPOINT ["/app/gucci/entrypoint.sh"]
CMD []
